# Generated by Django 2.2.7 on 2019-11-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, unique=True, verbose_name='用户ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='名称')),
                ('mobile', models.CharField(blank=True, default='', max_length=15, null=True, unique=True, verbose_name='手机号')),
                ('mobile_authenticated', models.BooleanField(default=False, verbose_name='手机认证状态')),
                ('remark', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='简介')),
                ('avatar_fpath', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='头像地址')),
                ('qr_fpath', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='名片二维码地址')),
                ('qr_fpath_white', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='名片二维码地址-白色背景图')),
                ('contact_mobile', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='联系电话')),
                ('intermediary_company', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='所属中介公司')),
                ('main_community', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='主营小区')),
                ('labels', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='主营板块')),
                ('sell_count', models.IntegerField(default=0, verbose_name='出售数量')),
                ('rent_count', models.IntegerField(default=0, verbose_name='出租数量')),
                ('view_count', models.IntegerField(default=0, verbose_name='名片浏览量pv')),
                ('view_count_uv', models.IntegerField(default=0, verbose_name='名片浏览量uv')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'user_info',
            },
        ),
    ]
