# Generated by Django 2.2.7 on 2019-11-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Broker',
            new_name='User_info',
        ),
    ]
