# Generated by Django 2.2.7 on 2019-11-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_one', '0002_auto_20191125_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='contact_mobile',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='intermediary_company',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='main_community',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='qr_fpath',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='qr_fpath_white',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='rent_count',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='sell_count',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='view_count_uv',
        ),
        migrations.AddField(
            model_name='user_info',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='密码'),
        ),
    ]
