# Generated by Django 2.2.7 on 2019-11-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_one', '0003_auto_20191126_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(default='', max_length=32, verbose_name='方案编号')),
                ('item_no', models.CharField(default='', max_length=32, verbose_name='商品编号')),
            ],
        ),
    ]
