# Generated by Django 2.2.7 on 2019-11-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_one', '0004_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='avatar_fpath',
        ),
    ]
