# Generated by Django 2.1 on 2019-11-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_one', '0005_remove_user_info_avatar_fpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='mobile_authenticated',
        ),
    ]
