# Generated by Django 2.1 on 2019-08-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_one', '0006_remove_user_info_mobile_authenticated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='remark',
            new_name='remarks',
        ),
    ]
