# Generated by Django 2.1 on 2020-08-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_one', '0007_auto_20191210_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(default='', max_length=32, verbose_name='IP地址')),
                ('count', models.IntegerField(default=0, verbose_name='当天访问次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '访问信息',
                'verbose_name_plural': '访问信息',
                'db_table': 'ip_info',
            },
        ),
    ]
