# Generated by Django 2.1 on 2020-12-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_one', '0008_ipinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户ID')),
                ('token', models.CharField(blank=True, default='', max_length=256, verbose_name='token')),
                ('overdue_time', models.DateTimeField(auto_now_add=True, verbose_name='过期时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户token',
                'verbose_name_plural': '用户token',
                'db_table': 'user_token',
            },
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='用户ID'),
        ),
    ]
