# Generated by Django 2.1 on 2020-12-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_one', '0009_auto_20201214_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='state',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='记录状态'),
        ),
        migrations.AddField(
            model_name='usertoken',
            name='state',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='记录状态'),
        ),
    ]
